# Basic
data_dir: '/blue/weishao/hongxu.jiang/3DFastDDPM/data/AOT_train_npy/'
result_dir: '/red/weishao/weishao/DPM_3D/output_AOT/'
batch_size: 4
patch_size: [128, 128, 128]
type: 'fast'   # 'fast' or 'ddpm'
dwt: False
f_steps: 3
extra_args: "fast_ts5_x0_ch64_s222_aot"

# Training
num_workers: 8
lr: 0.0001
weight_decay: 0.0001
ema_rate: "0.99"
log_interval: 100
save_interval: 20000

# Diffusion
noise_schedule: "linear"
diffusion_steps: 1000
timestep_respacing: ""
learn_sigma: False
sigma_small: False
use_kl: False
predict_xstart: 'x0'  # 'x0' or 'epsilon' or 'V'
rescale_timesteps: False
rescale_learned_sigmas: False

# UNet
in_channels: 2
model_channels: 64
out_channels: 1
strides: [2, 2, 2]
num_res_blocks: 2
channel_mult: [1, 1, 2, 2, 4]
attention_resolutions: [8]
dropout: 0.1
num_heads: 4
num_heads_upsample: -1
num_head_channels: -1

# Sampling
sample_dir: "/blue/weishao/hongxu.jiang/3DFastDDPM/data/AOT_sample_npy/"



